### ISSUE TITLE
unexpected error: The vpc ID 'vpc-6f0abf08' does not exist

### ISSUE THREAD

**Issue by troytop** [colstrom/cloudstrap#27]
```
$ cloudstrap
/usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:111:in `block in poll': stopped waiting due to an unexpected error: The vpc ID 'vpc-6f0abf08' does not exist (Aws::Waiters::Errors::UnexpectedError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:101:in `loop'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:101:in `poll'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:91:in `block (2 levels) in wait'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:90:in `block in wait'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:89:in `catch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/waiters/waiter.rb:89:in `wait'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.6.44/lib/aws-sdk-core/client_waiters.rb:110:in `wait_until'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.6.44/lib/aws-sdk-resources/operations.rb:229:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.6.44/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
	from /usr/local/lib/ruby/gems/2.4.0/gems/cloudstrap-0.42.2.pre/lib/cloudstrap/amazon/ec2.rb:282:in `create_vpc'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/cloudstrap-0.42.2.pre/lib/cloudstrap/agent.rb:31:in `create_vpc'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/cloudstrap-0.42.2.pre/lib/cloudstrap/agent.rb:275:in `vpc'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
	from /usr/local/lib/ruby/gems/2.4.0/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/cloudstrap-0.42.2.pre/bin/cloudstrap:56:in `<top (required)>'
	from /usr/local/bin/cloudstrap:22:in `load'
	from /usr/local/bin/cloudstrap:22:in `<main>'
```

The vpc listed is never actually created when cloudstrap is run.

**Comment by jandubois** [comment]
I get this error too when the `region` field in `config.yaml` is different from the value of the `AWS_REGION` environment variable.

In earlier days (pre 0.30?) I didn't even need `AWS_REGION`, but now both settings seem to be required.

**Comment by HartS** [comment]
I also encountered this error when setting an AWS_PROFILE which had a default region different from the region specified in config.yaml, because lines like https://github.com/colstrom/cloudstrap/blob/7baa244c9570c4b4304e193504c3527507684be7/lib/cloudstrap/amazon/ec2.rb#L280, which are designed to wait until the resource is available don't pass the region which is detected [here](https://github.com/colstrom/cloudstrap/blob/7baa244c9570c4b4304e193504c3527507684be7/lib/cloudstrap/config.rb#L13). Instead they fully rely on the environment variables set, which will end up using the AWS_REGION variable if set, or the region specified in ~/.aws/config for the AWS_PROFILE

Talked with Chris, and the solution is to pass the memoized Config#region (determined from `BOOTSTRAP_REGION` or config.yaml) to resource API invokations
